### ISSUE TITLE
"Can't redefine property: tap" error with Laravel Mix 4

### ISSUE THREAD

**Issue by NSpehler** [Douglasdc3/laravel-mix-svg#5]
Hello Ken,

I'm getting the following error when using this package alongside with Laravel Mix 4.0.14:

```
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js "--watch"

/PATH/node_modules/webpack-cli/bin/cli.js:235
                                throw err;
                                ^

TypeError: Cannot redefine property: tap
    at Function.defineProperty (<anonymous>)
    at Object.<anonymous> (/PATH/node_modules/laravel-mix-svg/node_modules/laravel-mix/src/helpers.js:21:8)
    at Module._compile (/PATH/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (/PATH/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/PATH/node_modules/laravel-mix-svg/node_modules/laravel-mix/src/index.js:16:1)
```

However, it worked great with Laravel Mix 2.1.14. I looked at the changelog and upgrade guide from Laravel Mix and I couldn't find a breaking change that could have caused this.

Did you ever come across this issue? Not sure how to go about debugging this...

Thanks,
Nicolas

**Comment by NSpehler** [comment]
Hello Ken,

Do you have any ideas/thoughts on what might cause this? Willing to do a PR if you have a hint.

Thanks,
Nicolas

**Comment by Douglasdc3** [comment]
@NSpehler Can you try out the latest version 0.3.0 has been just tagged. I updated laravel mix to v4. I was able to reproduce the issue.

Hopefully this resolves your issue. 

EDIT: Tested it one of my own projects and the upgrade seems to have worked. I also defined the peer dependency incorrect this seems to have broken during Laravel Mix 4 upgrade.

**Comment by NSpehler** [comment]
Works great in my project as well, thank you very much! 🙌
